config/routes.rb
NewsyNews::Application.routes.draw do
  get "welcome/index"

   root 'welcome#index'
   resources :stories, :only => [:show] 

  

end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	def show
		@story = Story.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@stories = Story.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsyNews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stories/show.html.erb
<h3>Story Info</h3>
<ul>
	<li>
Title: <%= @story.title %>
</li>
<li>
Link: <%= @story.link %>
</li>
<li>
Category: <%= @story.category %>
</li>
<li>
Upvotes: <%= @story.upvotes %>
</li>

app/views/welcome/index.html.erb
<h3>Welcome to Newsy News!</h3>
<% @stories.each do |story| %>
	<p>
	<%= link_to story.title, story_path(story.id) %>
	<% end %>